fix: serializing date and carbon objects
laravel/serializable-closure pull request #52
Opened 2022-07-19 12:37 UTC by yamenarahman

When trying to serialize properties that have date objects or carbon objects like when queuing a closure, I'm facing bugs/warnings similar to this: 
- `PHP Warning:  serialize(): "date" returned as member variable from __sleep()`
- `The DateTime object has not been correctly initialized by its constructor`

I found that the issue is with serializing the date objects and php version. Also found similar PRs.
https://github.com/opis/closure/issues/75
https://github.com/opis/closure/pull/113

2022-07-19 18:56 UTC, GrahamCampbell requested changes

2022-07-20 18:53 UTC, yamenarahman commented
This is my exact use case:
```php
dispatch(function () {
    AuditLog::create($this->attributes);
 })->onQueue('audit_logs');
```

`$attributes` is an array sometimes contains date and date time objects to be saved per model, ie: `'expired_at' => now()->addMonth()`.

After the changes of this PR it works fine. cc @nunomaduro

2022-07-25 10:37 UTC, nunomaduro commented
@yamenarahman Can you add tests on this pull requests please?

2022-07-25 11:38 UTC, yamenarahman commented
@nunomaduro Sure, can you please elaborate where to write the test? because I see 5 Reflection closures and multiple tests for PHP versions.

2022-07-25 13:41 UTC, nunomaduro commented
Take a look at the tests folder. There is hundreds of examples.

2022-07-28 17:12 UTC, nunomaduro commented
Please ask to this pull request to be re-open, once you add the tests.

2022-07-28 17:12 UTC, closed without merging